# Generated by Django 6.0.3 on 2026-03-03 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(max_length=255)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('partita_iva', models.CharField(blank=True, max_length=11)),
                ('email_contatto', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('data_registrazione', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'azienda'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Azienda',
                'verbose_name_plural': 'Aziende',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('indirizzo', models.CharField(max_length=255)),
                ('citta', models.CharField(max_length=100)),
                ('cap', models.CharField(blank=True, max_length=10)),
                ('provincia', models.CharField(blank=True, max_length=2)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedi', to='aziende.azienda')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedi',
            },
        ),
        migrations.CreateModel(
            name='Lavoratore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField()),
                ('codice_fiscale', models.CharField(max_length=16, unique=True)),
                ('mansione', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('attivo', models.BooleanField(default=True)),
                ('data_inserimento', models.DateTimeField(auto_now_add=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lavoratori', to='aziende.azienda')),
                ('user', models.OneToOneField(blank=True, limit_choices_to={'role': 'operatore'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lavoratori', to='aziende.sede')),
            ],
            options={
                'verbose_name': 'Lavoratore',
                'verbose_name_plural': 'Lavoratori',
                'ordering': ['cognome', 'nome'],
            },
        ),
    ]
