# Generated by Django 6.0.3 on 2026-03-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aziende', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='contratto_saldato',
            field=models.BooleanField(
                default=True,
                help_text='Se non saldato, l\'azienda vedra un avviso e le funzionalita saranno limitate.',
            ),
        ),
    ]
