# Generated by Django 6.0.3 on 2026-03-16 00:00

import apps.aziende.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aziende', '0002_azienda_contratto_saldato'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='protocollo_sanitario',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.aziende.models.upload_documento_azienda,
            ),
        ),
        migrations.AddField(
            model_name='azienda',
            name='nomina_medico',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.aziende.models.upload_documento_azienda,
            ),
        ),
        migrations.AddField(
            model_name='azienda',
            name='verbali_sopralluogo',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.aziende.models.upload_documento_azienda,
            ),
        ),
        migrations.AddField(
            model_name='azienda',
            name='varie_documento',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.aziende.models.upload_documento_azienda,
            ),
        ),
        migrations.AddField(
            model_name='azienda',
            name='varie_note',
            field=models.TextField(blank=True),
        ),
    ]
