# Generated by Django 6.0.3 on 2026-03-23 16:26

import apps.aziende.models
import apps.aziende.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aziende', '0003_azienda_documenti'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='codice_univoco',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='azienda',
            name='logo_azienda',
            field=models.FileField(null=True, upload_to=apps.aziende.models.upload_logo_azienda, validators=[apps.aziende.validators.validate_company_logo_upload]),
        ),
        migrations.AddField(
            model_name='azienda',
            name='pec',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='azienda',
            name='referente_azienda',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='nomina_medico',
            field=models.FileField(blank=True, null=True, upload_to=apps.aziende.models.upload_documento_azienda, validators=[apps.aziende.validators.validate_company_document_upload]),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='protocollo_sanitario',
            field=models.FileField(blank=True, null=True, upload_to=apps.aziende.models.upload_documento_azienda, validators=[apps.aziende.validators.validate_company_document_upload]),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='varie_documento',
            field=models.FileField(blank=True, null=True, upload_to=apps.aziende.models.upload_documento_azienda, validators=[apps.aziende.validators.validate_company_document_upload]),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='verbali_sopralluogo',
            field=models.FileField(blank=True, null=True, upload_to=apps.aziende.models.upload_documento_azienda, validators=[apps.aziende.validators.validate_company_document_upload]),
        ),
    ]
