# Generated by Django 6.0.3 on 2026-03-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aziende', '0004_azienda_profilazione_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='condizioni_pagamento_riservate',
            field=models.TextField(blank=True),
        ),
    ]
