# Generated by Django 6.0.3 on 2026-03-26 11:40

import apps.aziende.models
import apps.aziende.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aziende', '0005_azienda_condizioni_pagamento_riservate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAziendale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.aziende.models.upload_documento_azienda, validators=[apps.aziende.validators.validate_company_document_upload])),
                ('note', models.TextField(blank=True)),
                ('origine', models.CharField(choices=[('admin', 'Admin'), ('azienda', 'Azienda')], default='azienda', max_length=20)),
                ('data_caricamento', models.DateTimeField(auto_now_add=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti_generici', to='aziende.azienda')),
                ('caricato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti_aziendali_caricati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento aziendale',
                'verbose_name_plural': 'Documenti aziendali',
                'ordering': ['-data_caricamento', '-id'],
            },
        ),
    ]
