# Generated by Django 6.0.3 on 2026-03-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aziende', '0006_documentoaziendale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azienda',
            name='contratto_saldato',
            field=models.BooleanField(default=True, help_text="Se non saldato, l'azienda vedrà un avviso e le funzionalità saranno limitate."),
        ),
    ]
