# Generated by Django 6.0.3 on 2026-04-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aziende', '0007_alter_azienda_contratto_saldato'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavoratore',
            name='telefono',
            field=models.CharField(default='', max_length=20, verbose_name='Numero di telefono'),
        ),
    ]
