# Generated by Django 6.0.3 on 2026-04-03 10:30

import apps.aziende.models
import apps.aziende.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aziende', '0008_lavoratore_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azienda',
            name='codice_univoco',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='email_contatto',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='logo_azienda',
            field=models.FileField(blank=True, null=True, upload_to=apps.aziende.models.upload_logo_azienda, validators=[apps.aziende.validators.validate_company_logo_upload]),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='pec',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='referente_azienda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'azienda'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
