# Generated by Django 6.0.3 on 2026-04-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aziende', '0009_alter_azienda_optional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavoratore',
            name='sesso',
            field=models.CharField(blank=True, choices=[('M', 'Maschile'), ('F', 'Femminile')], default='', max_length=1),
        ),
    ]
