# Generated by Django 6.0.3 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aziende', '0010_lavoratore_sesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavoratore',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Numero di telefono'),
        ),
    ]
