# Generated by Django 6.0.3 on 2026-04-17 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aziende', '0011_alter_lavoratore_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='email_notifiche_cc',
            field=models.TextField(blank=True, default='', help_text="Indirizzi email che ricevono in cc le comunicazioni inviate all'account azienda principale. Inseriscine uno per riga oppure separali con una virgola."),
        ),
        migrations.CreateModel(
            name='AziendaReadOnlyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_only_accesses', to='aziende.azienda')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_read_only_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'azienda'}, on_delete=django.db.models.deletion.CASCADE, related_name='read_only_company_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accesso azienda in sola lettura',
                'verbose_name_plural': 'Accessi azienda in sola lettura',
                'ordering': ['user__email', 'pk'],
            },
        ),
    ]
