# Generated by Django 6.0.3 on 2026-03-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data creazione'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Attivo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Accesso amministrazione'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Amministratore'), ('azienda', 'Azienda / Datore di lavoro'), ('operatore', 'Operatore / Lavoratore')], max_length=20, verbose_name='Ruolo'),
        ),
    ]
