# Generated by Django 6.0.3 on 2026-03-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_data_creazione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_permissions',
            field=models.JSONField(blank=True, default=list, help_text='Elenco provvisorio dei permessi assegnati agli admin non superuser.', verbose_name='Permessi admin limitato'),
        ),
    ]
