# Generated by Django 6.0.3 on 2026-03-24 10:19

import apps.commerciale.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aziende', '0005_azienda_condizioni_pagamento_riservate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno_fattura', models.PositiveSmallIntegerField(default=apps.commerciale.models.current_year)),
                ('prefisso_numero', models.CharField(default='FPR', max_length=10)),
                ('numero_progressivo', models.PositiveIntegerField(blank=True, null=True)),
                ('data_fattura', models.DateField(default=django.utils.timezone.localdate)),
                ('data_accettazione_campione', models.DateField(blank=True, null=True)),
                ('indirizzo_fatturazione', models.CharField(blank=True, max_length=255)),
                ('condizioni_pagamento_riservate', models.TextField(blank=True)),
                ('modalita_pagamento', models.CharField(blank=True, max_length=255)),
                ('aliquota_iva', models.DecimalField(decimal_places=2, default=Decimal('22.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('esente_iva', models.CharField(blank=True, max_length=255)),
                ('esigibilita_iva', models.CharField(blank=True, default='IVA ad esigibilita immediata', max_length=255)),
                ('gdd', models.CharField(blank=True, max_length=255)),
                ('fine_mese', models.BooleanField(default=False)),
                ('scadenza', models.DateField(blank=True, null=True)),
                ('banca_appoggio', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('inviata_il', models.DateField(blank=True, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatture', to='aziende.azienda')),
            ],
            options={
                'verbose_name': 'Fattura',
                'verbose_name_plural': 'Fatture',
                'ordering': ['-data_fattura', '-anno_fattura', '-numero_progressivo'],
            },
        ),
        migrations.CreateModel(
            name='FatturaVoce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255)),
                ('quantita', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sconto_percentuale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('fattura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci', to='commerciale.fattura')),
            ],
            options={
                'verbose_name': 'Voce fattura',
                'verbose_name_plural': 'Voci fattura',
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Preventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_preventivo', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('data_preventivo', models.DateField(default=django.utils.timezone.localdate)),
                ('oggetto', models.CharField(max_length=255)),
                ('descrizione_oggetto', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('riferimento_commerciale', models.CharField(blank=True, max_length=255)),
                ('assistente_tecnico', models.CharField(blank=True, max_length=255)),
                ('giorni_lavorativi', models.PositiveIntegerField(blank=True, null=True)),
                ('durata_offerta', models.DateField(blank=True, null=True)),
                ('condizioni_pagamento_riservate', models.TextField(blank=True)),
                ('aliquota_iva', models.DecimalField(decimal_places=2, default=Decimal('22.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventivi', to='aziende.azienda')),
            ],
            options={
                'verbose_name': 'Preventivo',
                'verbose_name_plural': 'Preventivi',
                'ordering': ['-data_preventivo', '-numero_preventivo'],
            },
        ),
        migrations.CreateModel(
            name='PreventivoVoce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255)),
                ('quantita', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sconto_percentuale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('preventivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci', to='commerciale.preventivo')),
            ],
            options={
                'verbose_name': 'Voce preventivo',
                'verbose_name_plural': 'Voci preventivo',
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='fattura',
            constraint=models.UniqueConstraint(fields=('anno_fattura', 'prefisso_numero', 'numero_progressivo'), name='commerciale_fattura_numero_unico'),
        ),
    ]
