# Generated by Django 6.0.3 on 2026-03-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerciale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fattura',
            name='cap_fatturazione',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fattura',
            name='categoria_merceologica',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fattura',
            name='causale',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fattura',
            name='comune_fatturazione',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fattura',
            name='data_incasso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fattura',
            name='provincia_fatturazione',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
