# Generated by Django 6.0.3 on 2026-04-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerciale', '0002_fattura_cap_fatturazione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivovoce',
            name='descrizione',
            field=models.TextField(),
        ),
    ]
