# Generated by Django 6.0.3 on 2026-03-03 17:04

import apps.sanitaria.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aziende', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartellaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_apertura', models.DateField(auto_now_add=True)),
                ('note_medico', models.TextField(blank=True)),
                ('lavoratore', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cartella', to='aziende.lavoratore')),
            ],
            options={
                'verbose_name': 'Cartella Clinica',
                'verbose_name_plural': 'Cartelle Cliniche',
            },
        ),
        migrations.CreateModel(
            name='DocumentoSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('referto', 'Referto'), ('verbale_visita', 'Verbale di visita'), ('esame', 'Risultato esame'), ('altro', 'Altro')], max_length=20)),
                ('titolo', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.sanitaria.models.upload_documento)),
                ('data', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('caricato_il', models.DateTimeField(auto_now_add=True)),
                ('cartella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='sanitaria.cartellaclinica')),
            ],
            options={
                'verbose_name': 'Documento Sanitario',
                'verbose_name_plural': 'Documenti Sanitari',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='EsitoIdoneita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esito', models.CharField(choices=[('idoneo', 'Idoneo'), ('idoneo_limitazioni', 'Idoneo con limitazioni'), ('non_idoneo', 'Non idoneo'), ('non_idoneo_temporaneo', 'Non idoneo temporaneo')], max_length=30)),
                ('mansione', models.CharField(max_length=255)),
                ('data_visita', models.DateField()),
                ('data_scadenza', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('comunicato_azienda', models.BooleanField(default=False)),
                ('data_comunicazione', models.DateTimeField(blank=True, null=True)),
                ('lavoratore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idoneita', to='aziende.lavoratore')),
            ],
            options={
                'verbose_name': 'Esito Idoneità',
                'verbose_name_plural': 'Esiti Idoneità',
                'ordering': ['-data_visita'],
            },
        ),
    ]
