# Generated by Django 6.0.3 on 2026-03-16 00:00

import apps.sanitaria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esitoidoneita',
            name='certificato',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.sanitaria.models.upload_certificato_idoneita,
            ),
        ),
    ]
