# Generated by Django 6.0.3 on 2026-03-31 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanitaria', '0002_esitoidoneita_certificato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esitoidoneita',
            options={'ordering': ['-data_visita'], 'verbose_name': 'Esito idoneità', 'verbose_name_plural': 'Esiti idoneità'},
        ),
    ]
