# Generated by Django 6.0.3 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitaria', '0003_alter_esitoidoneita_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esitoidoneita',
            name='esito',
            field=models.CharField(choices=[('idoneo', 'Idoneo'), ('idoneo_limitazioni', 'Idoneo con limitazioni'), ('idoneita_prescrizione', 'Idoneità con prescrizione'), ('non_idoneo', 'Non idoneo'), ('non_idoneo_temporaneo', 'Non idoneo temporaneo')], max_length=30),
        ),
    ]
