# Generated by Django 6.0.3 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitaria', '0004_alter_esitoidoneita_esito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esitoidoneita',
            name='esito',
            field=models.CharField(choices=[('idoneo', 'Idoneità confermata'), ('idoneo_limitazioni', 'Idoneità con limitazioni'), ('idoneita_prescrizione', 'Idoneità con prescrizione'), ('idoneo_prescrizioni_limitazioni', 'Idoneità con prescrizioni e limitazioni'), ('non_idoneo', 'Idoneità non confermata'), ('non_idoneo_temporaneo', 'Idoneità non confermata (temporanea)')], max_length=35),
        ),
    ]
